[package]
name = "rigseed"
version = "0.1.0"
description = "A desktop client for qBittorrent"
authors = ["Verastack Labs"]
license = "Apache-2.0"
repository = "https://github.com/verastack-labs/rigseed-app"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rigseed_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.3", features = [] }
tauri-plugin-log = "2"
tauri-plugin-shell = "2"
tauri-plugin-store = "2"
tauri-plugin-opener = "2"
rand = "0.8"
keyring = { version = "3", features = ["windows-native", "apple-native", "sync-secret-service"] }
thiserror = "2"
sha2 = { version = "0.10.9", default-features = false, features = ["std"] }
base64 = "0.23.1"
hmac = "0.12.1"
pbkdf2 = { version = "0.12", default-features = false, features = ["hmac"] }
tauri-plugin-http = "2.5.9"
reqwest = { version = "0.13.3", default-features = false, features = ["json", "multipart", "cookies", "rustls", "http2", "query", "form", "charset"] }
resvg = "0.45.1"
tauri-plugin-dialog = "2.7.2"

[dev-dependencies]
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros"] }
