#!/usr/bin/env node
//
// Writes rigseed-mark.svg from rigseed-mark.template.svg, filling in the
// default accent's sky.
//
// The template is the only place the drawing exists. src/icon.rs substitutes
// the same two tokens at runtime for whichever accent the user picked, so
// running this is what keeps the packaged icon and the themed one the same
// picture rather than two that merely started out alike.
//
//   node scripts/build-icon.mjs && pnpm tauri icon src-tauri/icons/rigseed-mark.svg

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const icons = join(root, 'src-tauri', 'icons')

// dustblue, dark. Must match the fallback arm of `field()` in src/icon.rs.
const DEFAULT_SKY = { top: '#5A8AAA', bottom: '#2B5069' }

const template = readFileSync(join(icons, 'rigseed-mark.template.svg'), 'utf8')

for (const token of ['SKY_TOP', 'SKY_BOTTOM']) {
  if (!template.includes(token)) {
    console.error(`error: the template has no ${token}. Has it been edited by hand?`)
    process.exit(1)
  }
}

const svg = template
  .replace('SKY_TOP', DEFAULT_SKY.top)
  .replace('SKY_BOTTOM', DEFAULT_SKY.bottom)
  .replace(
    '<!--',
    '<!--\n    GENERATED by scripts/build-icon.mjs. Edit rigseed-mark.template.svg.\n',
  )

writeFileSync(join(icons, 'rigseed-mark.svg'), svg)
console.log(`wrote rigseed-mark.svg with sky ${DEFAULT_SKY.top} to ${DEFAULT_SKY.bottom}`)
console.log('next: pnpm tauri icon src-tauri/icons/rigseed-mark.svg')
